name: build and push

on:
  push:
    branches:
    - master
    paths:
    - './php-fpm/Dockerfile'

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./php-fpm
        file: ./php-fpm/Dockerfile
        platforms: linux/amd64,linux/armhf
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm
